apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "epidemic-mgr.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  host: "{{ include "epidemic-mgr.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
  subsets:
  - name: v1
    labels:
      version: 1.0.0
